project_name: "Vulnerability Detection Binary"
run_name: "RankFromSets"

data:
  train_path: "data/train_data.pkl"
  val_path: "data/val_data.pkl"
  test_path: "data/train_data.pkl"

model:
  model_name: "rankfromsets"
  classes: 2
  emb_size: 100
  mode: "mean"
  max_length: 512

run:
  batch_size: 256
  num_workers: 0
  scheduler: ""
  scheduler_period: "None"
  optimizer: "adamW"
  learning_rate: 0.001
  betas: (0.99,0.999)
  weight_decay: 0.01
  num_epochs: 10
  eval_batch_size: 256
  save_state: True
